#ifndef __PG_HEADER_H
#define __PG_HEADER_H

#include <arpa/inet.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include "dirent.h"
#include "fcntl.h"
#include "sys/stat.h"
#include "postgres.h"
#include "fmgr.h"
#include "postmaster/bgworker.h"
#include "catalog/pg_authid.h"
#include "storage/ipc.h"
#include "pgstat.h"
#include "access/genam.h"
#include "access/heapam.h"
#include "access/xact.h"
#include "utils/fmgroids.h"
#include "utils/lsyscache.h"
#include "utils/builtins.h"
#include "utils/pg_lsn.h"
#include "commands/dbcommands.h"
#include "miscadmin.h"
#include "funcapi.h"
#include "catalog/namespace.h"
#include "commands/extension.h"
#include "replication/walsender.h"
#include "replication/walsender_private.h"
#include "storage/procarray.h"
#include "common/ip.h"
#include "optimizer/cost.h"
#include "utils/numeric.h"
#include "sys/ioctl.h"
#include "libpq-fe.h"
#include "net/if.h"
#include "netinet/in.h"
#include "nodes/pg_list.h"
#include "postmaster/postmaster.h"
#include "access/htup_details.h"
#include "access/reloptions.h"
#include "catalog/indexing.h"
#include "catalog/pg_foreign_data_wrapper.h"
#include "catalog/pg_foreign_server.h"
#include "catalog/pg_type.h"
#include "catalog/pg_user_mapping.h"
#include "executor/spi.h"
#include "foreign/foreign.h"
#include "lib/stringinfo.h"
#include "libpq-int.h"
#include "libpq/pqsignal.h"
#include "mb/pg_wchar.h"
#include "parser/scansup.h"
#include "utils/acl.h"
#include "utils/guc.h"
#include "utils/memutils.h"
#include "utils/rel.h"
#include "utils/varlena.h"

#endif
